### ISSUE TITLE
pg adapter

### ISSUE THREAD

**Issue by reharik** [neonerd/puresql#1]
Hey, I use pg, I took the mssql adapter changed 
`connection.Request().query`
 line and changed that to
`connection.query` 
and it works for pg.  could we include that in the source?  I could do a pull request if you like.
Also I found it a bit difficult to know where puresql was looking for my .sql file.  I figured it out, and perhaps I'm slow because I suck at referencing files system, but it might be good to add a little like about that in the docs.
Thanks let me know what you think
Raif

**Comment by reharik** [comment]
actually it's kind of hard to pass the path to the puresql queryloader, because you may call it from many different places in the app.  seems like if we could either specify the sql folder explicitly and then indvidual calls will be relative to that or if we could require the actual sql file and pass that either of those would work.
let me know i could do either of those.
r

**Comment by neonerd** [comment]
Hi Raif,

as far as Postgresql is concerned, feel free to make the pull request, will gladly include it. Did not have time to play with this on PQSQL project yet myself. :)

Loading queries - the puresql.loadQueries() function takes a normal file path as a parameter, it does not process it any way, so the same rules as if opening a file using node's "fs" module apply. Therefore, the safest way is to provide absolute path by using __dirname.

But I'll make a note of this and provide a more concise documentation example, thanks for spotting that.

I'm not sure about your usecase, but I usually load all queries in a separate module and then require that module from other files / controllers / etc.

```
-- app
-- -- index.js
-- -- queries.sql
-- -- queries.js
-- -- controllers
-- -- -- users.js
-- -- -- dogs.js
```

```
// queries.js

const queries = puresql.loadQueries(path.join(__dirname, 'queries.sql'))
module.exports = queries
```

```
// users.js

const queries = require('../queries')

...
```

Of course, you can include multiple "submodules" in queries.js and have it export an object, etc..

I find this way to be the most efficient one, as if you would be loading the queries separately for example in each controller, you'd be wasting memory if using the same queries file in multiple controllers.

**Comment by neonerd** [comment]
PG adapter with tests added in 1.4.0.

**Comment by reharik** [comment]
sorry, I didn't seem to get any of the email alerts.  I like your idea of loading in a seperate module and then just  requiring that.  
Thanks for both the pg and the idea!
r
