### ISSUE TITLE
How to use LIKE % :foo %

### ISSUE THREAD

**Issue by steadweb** [neonerd/puresql#9]
I can't see any supporting documentation around `LIKE` with MySQL. Does this library support that?

**Comment by steadweb** [comment]
I've figured this out with `:!foo`

**Comment by neonerd** [comment]
Hi, this is one options, but the safer one would be just to pass 

```'%'+variable+'%'```

into :foo, as with :!foo you are exposing yourself to an SQL injection if you do not sanitize the input separately.

**Comment by steadweb** [comment]
Thanks @neonerd.

If I pass the following won't it escape the input with `\`? 
```
{ "foo" : `"%${variable}%"` }
```
